### ISSUE TITLE
English dictionary public API suggestions?

### ISSUE THREAD

**Issue by khzaw** [khzaw/athena#3]

**Comment by yelinaung** [comment]
Just saw this one on HN https://www.wordsapi.com

GET `https://www.wordsapi.com/words/cat?accessToken=[yourToken]`

Response

```
{
  "results": [
    {
      "definition": "an informal term for a youth or man",
      "partOfSpeech": "noun",
      "synonyms": [
        "bozo",
        "guy",
        "hombre",
        "sod"
      ],
      "typeOf": [
        "adult male",
        "man"
      ]
    }
  ]
}
```

**Comment by yelinaung** [comment]
And the wrappers
http://restunited.com/releases/424223873313015558/wrappers

**Comment by khzaw** [comment]
@yelinaung Thanks. I haven't had time to work on athena yet. But will definitely look into it, when I can.
